import os
os.chdir(r"C:\Users\russo\EntraPass")
bt = chr(96)

code = []
code.append('export class Analyzer {')
code.append('  analyzeAll(data) {')
code.append('    const passkeyReadiness = this.analyzePasskeyReadiness(data);')
code.append('    const appCompatibility = this.analyzeAppCompatibility(data);')
code.append('    const policyAnalysis = this.analyzePolicies(data);')
code.append('    const authMethods = this.analyzeAuthMethods(data);')
code.append('    const toxicCombos = this.findToxicCombinations(passkeyReadiness, data);')
code.append('    const recommendations = this.generateRecommendations(passkeyReadiness, appCompatibility, policyAnalysis, authMethods, toxicCombos);')
code.append('    const narrative = this.generateNarrative(passkeyReadiness, appCompatibility, policyAnalysis, toxicCombos);')
code.append('    return {')
code.append('      passkeyReadiness,')
code.append('      apps: appCompatibility,')
code.append('      policies: policyAnalysis,')
code.append('      authMethods,')
code.append('      toxicCombos,')
code.append('      recommendations,')
code.append('      narrative,')
code.append('      timestamp: new Date().toISOString(),')
code.append('      tenantName: data.org?.displayName || "Unknown",')
code.append('    };')
code.append('  }')
code.append("")
code.append('  analyzePasskeyReadiness({ users = [], devices = [], policies = [], authMethodsConfig = [] }) {')
code.append('    const result = {')
code.append('      total: users.length,')
code.append('      ready: 0,')
code.append('      needsAttention: 0,')
code.append('      blocked: 0,')
code.append('      readyUsers: [],')
code.append('      attentionUsers: [],')
code.append('      blockedUsers: [],')
code.append('      breakdown: {')
code.append('        byDevice: { ready: 0, outdated: 0, none: 0 },')
code.append('        byAuthMethod: { hasPasskey: 0, hasMfa: 0, passwordOnly: 0 },')
code.append('        byPolicy: { blocked: 0, allowed: 0 },')
code.append('      },')
code.append('    };')
code.append("")
code.append('    const blockingPolicies = policies.filter(p => this.policyBlocksPasskeyRegistration(p));')
code.append("")
code.append('    users.forEach(user => {')
code.append('      const issues = [];')
code.append('      const details = { hasPasskeyMethod: false, hasMfaMethod: false, modernDevice: false, blockedByPolicy: false };')
code.append("")
code.append('      // Auth method analysis')
code.append('      const authMethods = user.authMethods || [];')
code.append("      authMethods.forEach(m => {")
code.append("        if (m.authenticationMethodType?.includes('passkey') || m.authenticationMethodType?.includes('fido2'))")
code.append("          details.hasPasskeyMethod = true;")
code.append("        if (m.authenticationMethodType?.includes('microsoftAuthenticator') ||")
code.append("            m.authenticationMethodType?.includes('phone') ||")
code.append("            m.authenticationMethodType?.includes('temporaryAccessPass'))")
code.append("          details.hasMfaMethod = true;")
code.append('      });')
code.append("      if (!details.hasMfaMethod) issues.push('No MFA method registered');")
code.append("      if (details.hasPasskeyMethod) issues.push('Already has passkey/FIDO2 registered');")
code.append("")
code.append('      // Device analysis')
code.append('      const userDevices = devices.filter(d => {')
code.append('        const owners = d.registeredOwners || [];')
code.append('        return owners.some(o => o.id === user.id || o.userPrincipalName === user.userPrincipalName);')
code.append("      });")
code.append("")
code.append("      userDevices.forEach(d => {")
code.append("        const os = (d.operatingSystem || '').toLowerCase();")
code.append("        const ver = parseInt(d.operatingSystemVersion) || 0;")
code.append("        if ((os.includes('windows') && ver >= 10) ||")
code.append("            (os.includes('ios') && ver >= 16) ||")
code.append("            (os.includes('android') && ver >= 14) ||")
code.append("            (os.includes('mac') && ver >= 13))")
code.append("          details.modernDevice = true;")
code.append("      });")
code.append("")
code.append("      if (details.modernDevice) result.breakdown.byDevice.ready++;")
code.append("      else if (userDevices.length > 0) result.breakdown.byDevice.outdated++;")
code.append("      else result.breakdown.byDevice.none++;")
code.append("")
code.append("      if (!details.modernDevice && userDevices.length > 0)")
code.append("        issues.push('Device OS outdated for passkeys');")
code.append("      if (userDevices.length === 0 && !details.hasPasskeyMethod)")
code.append("        issues.push('No compatible device registered');")
code.append("")
code.append("      // Auth method stats')
code.append("      if (details.hasPasskeyMethod) result.breakdown.byAuthMethod.hasPasskey++;")
code.append("      if (details.hasMfaMethod) result.breakdown.byAuthMethod.hasMfa++;")
code.append("      if (!details.hasMfaMethod && !details.hasPasskeyMethod)")
code.append("        result.breakdown.byAuthMethod.passwordOnly++;")
code.append("")
code.append("      // Policy check')
code.append("      blockingPolicies.forEach(p => {")
code.append("        if (p.conditions?.users?.includeUsers?.includes('All') ||")
code.append("            p.conditions?.users?.includeUsers?.includes(user.id)) {")
code.append("          issues.push('Blocked by CA policy: ' + p.displayName);")
code.append("          details.blockedByPolicy = true;")
code.append("        }")
code.append("      });")
code.append("")
code.append("      if (details.blockedByPolicy) result.breakdown.byPolicy.blocked++;")
code.append("      else result.breakdown.byPolicy.allowed++;")
code.append("")
code.append("      let status = 'ready';")
code.append("      if (issues.length > 0) {")
code.append("        status = details.blockedByPolicy ? 'blocked' : 'attention';")
code.append("      }")
code.append("")
code.append("      const userEntry = {")
code.append("        id: user.id,")
code.append("        displayName: user.displayName || user.userPrincipalName,")
code.append("        userPrincipalName: user.userPrincipalName,")
code.append("        status,")
code.append("        issues,")
code.append("        details,")
code.append("        deviceCount: userDevices.length,")
code.append("        authMethodCount: authMethods.length,")
code.append("        groups: (user.groups || []).map(g => g.displayName),")
code.append("        lastSignIn: user.signInActivity?.lastSuccessfulSignIn || null,")
code.append("      };")
code.append("")
code.append("      if (status === 'ready') { result.ready++; result.readyUsers.push(userEntry); }")
code.append("      else if (status === 'attention') { result.needsAttention++; result.attentionUsers.push(userEntry); }")
code.append("      else { result.blocked++; result.blockedUsers.push(userEntry); }")
code.append("    });")
code.append("")
code.append("    return result;")
code.append('  }')
code.append("")
code.append('  analyzeAppCompatibility({ apps = [], servicePrincipals = [] }) {')
code.append('    return [...apps, ...servicePrincipals].map(app => {')
code.append('      const issues = [];')
code.append('      let passkeyCompatible = true;')
code.append('')
code.append('      if (app.signInAudience === "AzureADMyOrg" && !app.requiredResourceAccess?.length)')
code.append("        issues.push('No delegated permissions - may use legacy auth workflow');")
code.append('')
code.append('      if (app.passwordCredentials?.length > 0) {')
code.append("        issues.push('Has password credentials (ROPC/legacy auth not passkey compatible)');")
code.append('        passkeyCompatible = false;')
code.append('      }')
code.append('')
code.append('      if (app.keyCredentials?.length > 0) {')
code.append("        issues.push('Uses certificate-based auth - verify passkey support');")
code.append('      }')
code.append('')
code.append('      if (app.appRoles?.length > 0) {')
code.append("        issues.push('Has app roles defined - ensure SAML/OIDC configuration supports passkeys');")
code.append('      }')
code.append('')
code.append("      return {")
code.append("        id: app.id,")
code.append("        displayName: app.displayName || 'Unnamed App',")
code.append("        passkeyCompatible: issues.length === 0,")
code.append("        issues,")
code.append("        fixGuide: passkeyCompatible ? null : this.getAppFixGuide(issues),")
code.append("      };")
code.append("    }).filter(a => a.displayName !== 'Unnamed App');")
code.append('  }')
code.append("")
code.append('  getAppFixGuide(issues) {')
code.append("    const guides = [];")
code.append("    if (issues.some(i => i.includes('password credentials') || i.includes('ROPC')))")
code.append("      guides.push('Remove password credentials. Migrate to OAuth 2.0 OIDC with PKCE.');")
code.append("    if (issues.some(i => i.includes('legacy auth')))")
code.append("      guides.push('Configure delegated permissions in Azure Portal App Registration > API Permissions.');")
code.append("    return guides.join(' ');")
code.append('  }')
code.append("")
code.append('  analyzePolicies({ policies = [] }) {')
code.append('    return policies.map(policy => {')
code.append('      const blocks = this.policyBlocksPasskeyRegistration(policy);')
code.append('      const warning = blocks ? "This policy requires password as a grant control, which blocks passkey-only authentication."')
code.append('        : null;')
code.append('')
code.append('      return {')
code.append('        id: policy.id,')
code.append('        displayName: policy.displayName,')
code.append('        state: policy.state,')
code.append('        blocksPasskeyRegistration: blocks,')
code.append('        warning,')
code.append('        fixGuide: blocks')
code.append("          ? 'Create a separate CA policy for passkey-capable users that requires FIDO2 authentication strength instead of password.'")
code.append('          : null,')
code.append('        details: {')
code.append('          grantControls: policy.grantControls,')
code.append('          conditions: {')
code.append('            users: policy.conditions?.users,')
code.append('            applications: policy.conditions?.applications,')
code.append('          },')
code.append('        },')
code.append('      };')
code.append('    });')
code.append('  }')
code.append("")
code.append('  analyzeAuthMethods({ users = [], authMethodsConfig = [] }) {')
code.append('    const configs = {};')
code.append('    authMethodsConfig.forEach(m => {')
code.append('      if (m.id) configs[m.id] = {')
code.append('        state: m.state,')
code.append('        enabled: m.state === "enabled",')
code.append('      };')
code.append('    });')
code.append('')
code.append('    // Count users with passkey methods')
code.append('    let withPasskey = 0, withMfa = 0;')
code.append('    users.forEach(u => {')
code.append('      const methods = u.authMethods || [];')
code.append('      if (methods.some(m => m.authenticationMethodType?.toLowerCase().includes("fido") ||')
code.append('          m.authenticationMethodType?.toLowerCase().includes("passkey")))')
code.append('        withPasskey++;')
code.append('      if (methods.length > 0) withMfa++;')
code.append('    });')
code.append('')
code.append('    return {')
code.append('      fido2Config: configs["Fido2"] || { state: "unknown" },')
code.append('      microsoftAuthenticatorConfig: configs["MicrosoftAuthenticator"] || { state: "unknown" },')
code.append('      temporaryAccessPassConfig: configs["TemporaryAccessPass"] || { state: "unknown" },')
code.append('      usersWithPasskey: withPasskey,')
code.append('      usersWithMfa: withMfa,')
code.append('    };')
code.append('  }')
code.append("")
code.append('  findToxicCombinations(passkeyReadiness, { users = [], policies = [] }) {')
code.append('    const combos = [];')
code.append('')
code.append('    // Toxic combo 1: High-privilege role + no passkey + no MFA')
code.append('    const highPrivilegeUsers = [];')
code.append('    users.forEach(u => {')
code.append('      const groups = (u.groups || []).map(g => g.displayName.toLowerCase());')
code.append('      const isPrivileged = groups.some(g =>')
code.append("        g.includes('admin') || g.includes('global') ||")
code.append("        g.includes('privileged') || g.includes('exchange') ||")
code.append("        g.includes('sharepoint') || g.includes('user administrator')"); // fixed typo 'SharePoint'
code.append('      );')
code.append('      if (isPrivileged) {')
code.append('        const hasPasskey = (u.authMethods || []).some(m =>')
code.append('          m.authenticationMethodType?.toLowerCase().includes("fido") ||')
code.append('          m.authenticationMethodType?.toLowerCase().includes("passkey"));')
code.append('        const hasMfa = (u.authMethods || []).length > 0;')
code.append('        if (!hasPasskey && !hasMfa) {')
code.append('          highPrivilegeUsers.push({')
code.append('            displayName: u.displayName || u.userPrincipalName,')
code.append('            groups: (u.groups || []).map(g => g.displayName),')
code.append('            severity: "critical",')
code.append('            description: "High-privilege user with NO MFA and NO passkey. Single password compromise = full tenant takeover.",')
code.append('            fix: "Enable MFA immediately. Register passkey/FIDO2 as primary auth method.",')
code.append('          });')
code.append('        }')
code.append('      }')
code.append('    });')
code.append('    combos.push(...highPrivilegeUsers);')
code.append('')
code.append('    // Toxic combo 2: Passkey enabled but CA allows password fallback')
code.append('    const vulnerablePolicies = policies.filter(p => {')
code.append('      if (p.state === "disabled") return false;')
code.append('      const gc = p.grantControls;')
code.append('      if (!gc) return false;')
code.append('      // Policy allows password as one of multiple controls')
code.append('      return gc.builtInControls?.includes("password") &&')
code.append('        gc.builtInControls?.includes("mfa");')
code.append('    });')
code.append('    if (vulnerablePolicies.length > 0) {')
code.append('      combos.push({')
code.append('        severity: "high",')
code.append('        displayName: "Password fallback enabled alongside passkey",')
code.append("        description: vulnerablePolicies.length + ' CA policies allow password as fallback even when passkey is used. Users can bypass passkey by choosing password.',")
code.append("        fix: 'Update CA policies to require FIDO2 authentication strength for passkey-capable users.',")
code.append('      });')
code.append('    }')
code.append('')
code.append('    // Toxic combo 3: Global admin with no passkey')
code.append('    return combos;')
code.append('  }')
code.append("")
code.append('  policyBlocksPasskeyRegistration(policy) {')
code.append("    if (policy.state === 'disabled') return false;")
code.append("    const gc = policy.grantControls;")
code.append("    if (!gc) return false;")
code.append("    return gc.builtInControls?.includes('password') || false;")
code.append('  }')
code.append("")
code.append('  generateRecommendations(passkeyReadiness, appCompatibility, policyAnalysis, authMethods, toxicCombos) {')
code.append('    const recs = [];')
code.append('')
code.append('    // Critical')
code.append('    toxicCombos.filter(t => t.severity === "critical").forEach(t => {')
code.append('      recs.push({ severity: "critical", icon: "??", category: "Security Risk",')
code.append('        title: t.displayName || "High-privilege user vulnerable",')
code.append('        text: t.description,')
code.append("        fix: t.fix,")
code.append('      });')
code.append('    });')
code.append('')
code.append('    // High')
code.append('    policyAnalysis.filter(p => p.blocksPasskeyRegistration).forEach(p => {')
code.append('      recs.push({ severity: "high", icon: "??", category: "Policy Blocking",')
code.append("        title: 'CA policy blocks passkeys: ' + p.displayName,")
code.append("        text: p.warning || 'Blocks passkey registration',")
code.append("        fix: p.fixGuide || 'Review and update policy',")
code.append('      });')
code.append('    });')
code.append('')
code.append('    if (passkeyReadiness.blocked > 0) {')
code.append('      recs.push({ severity: "high", icon: "??", category: "Blocked Users",')
code.append('        title: bt + "${passkeyReadiness.blocked} user(s) completely blocked from passkeys" + bt + "",')
code.append('        text: "These users cannot register passkeys due to policies or device limitations.",')
code.append("        fix: 'Review blocked users list and address device/policy issues individually.',")
code.append('      });')
code.append('    }')
code.append('')
code.append('    // Medium')
code.append('    if (passkeyReadiness.needsAttention > 0) {')
code.append('      recs.push({ severity: "medium", icon: "??", category: "Needs Attention",')
code.append('        title: bt + "${passkeyReadiness.needsAttention} user(s) need preparation" + bt + "",')
code.append('        text: "These users have devices or auth methods that need updating.",')
code.append("        fix: 'Guide users to register modern devices and set up Microsoft Authenticator.',")
code.append('      });')
code.append('    }')
code.append('')
code.append('    const badApps = appCompatibility.filter(a => !a.passkeyCompatible);')
code.append('    if (badApps.length > 0) {')
code.append('      recs.push({ severity: "medium", icon: "??", category: "App Compatibility",')
code.append('        title: bt + "${badApps.length} app(s) not passkey compatible" + bt + "",')
code.append("        text: badApps.map(a => a.displayName).join(', '),")
code.append("        fix: 'Review each app. Most issues are fixable by updating auth configuration.'")
code.append('      });')
code.append('    }')
code.append('')
code.append('    // Good news')
code.append('    if (passkeyReadiness.ready > 0) {')
code.append('      recs.push({ severity: "low", icon: "??", category: "Ready",')
code.append('        title: bt + "${passkeyReadiness.ready} user(s) ready for passkeys!" + bt + "",')
code.append("        text: 'Start a pilot program with these users.',")
code.append("        fix: 'Enable passkey registration for pilot group and monitor sign-in logs.'")
code.append('      });')
code.append('    }')
code.append('')
code.append('    if (recs.length === 0) {')
code.append('      recs.push({ severity: "low", icon: "?", category: "All Clear",')
code.append("        title: 'Tenant looks ready for passkey migration!',")
code.append("        text: 'Great job keeping your tenant passkey-ready.',")
code.append("        fix: 'Proceed with enabling passkey registration across the tenant.'")
code.append('      });')
code.append('    }')
code.append('')
code.append('    return recs;')
code.append('  }')
code.append("")
code.append('  generateNarrative(passkeyReadiness, appCompatibility, policyAnalysis, toxicCombos) {')
code.append('    const parts = [];')
code.append('')
code.append('    // Tenant overview')
code.append('    const total = passkeyReadiness.total;')
code.append('    parts.push("Tenant has " + total + " users total.");')
code.append('')
code.append('    if (passkeyReadiness.ready > 0) {')
code.append('      parts.push(bt + "?? " + passkeyReadiness.ready + " out of " + total + " users are READY for passkeys right now." + bt + "");')
code.append('      if (passkeyReadiness.readyUsers.length > 0) {')
code.append('        const sampleUsers = passkeyReadiness.readyUsers.slice(0, 3).map(u => u.displayName).join(", ");')
code.append('        parts.push("Example ready users: " + sampleUsers);')
code.append('      }')
code.append('    }')
code.append('')
code.append('    if (passkeyReadiness.needsAttention > 0) {')
code.append('      parts.push(bt + "?? " + passkeyReadiness.needsAttention + " users need attention. Most common issues: outdated devices or missing MFA." + bt + "");')
code.append('    }')
code.append('')
code.append('    if (passkeyReadiness.blocked > 0) {')
code.append('      parts.push(bt + "?? " + passkeyReadiness.blocked + " users are BLOCKED from using passkeys." + bt + "");')
code.append('      const blockedPolicies = policyAnalysis.filter(p => p.blocksPasskeyRegistration);')
code.append('      if (blockedPolicies.length > 0) {')
code.append('        parts.push("Blocking policies: " + blockedPolicies.map(p => p.displayName).join(", "));')
code.append('      }')
code.append('    }')
code.append('')
code.append('    // Toxic combos')
code.append('    if (toxicCombos.length > 0) {')
code.append('      parts.push("");')
code.append('      parts.push("?? TOXIC COMBINATIONS FOUND:");')
code.append('      toxicCombos.forEach(t => {')
code.append('        parts.push("  " + t.severity.toUpperCase() + ": " + (t.description || t.fix));')
code.append('      });')
code.append('    }')
code.append('')
code.append('    // Auth methods')
code.append('    const withPasskey = passkeyReadiness.breakdown?.byAuthMethod?.hasPasskey || 0;')
code.append('    if (withPasskey > 0) {')
code.append('      parts.push("");')
code.append('      parts.push(withPasskey + " user(s) already have passkey/FIDO2 registered. They can help champion the rollout.");')
code.append('    }')
code.append('')
code.append('    // Passkey enrollment guidance')
code.append('    if (passkeyReadiness.ready > 0) {')
code.append('      parts.push("");')
code.append('      parts.push("?? PHASED ROLLOUT PLAN:");')
code.append('      parts.push("  Phase 1: Pilot with " + passkeyReadiness.ready + " ready users");')
code.append('      parts.push("  Phase 2: Enable passkey for attention users after device updates");')
code.append('      parts.push("  Phase 3: Resolve blocking policies for blocked users");')
code.append('      parts.push("  Phase 4: Full rollout with MFA phase-out");')
code.append('    }')
code.append('')
code.append('    return parts.join("\\n");')
code.append('  }')
code.append('}')
code.append('')

with open("src/analyzer.js", "w", encoding="utf-8") as f:
    f.write("\n".join(code))

print("analyzer.js completely rewritten with AI-level analysis")
