<#
.SYNOPSIS
  Exports all Cloudflare security rules for aboutcloud.io to JSON + Markdown.

.DESCRIPTION
  Queries the Cloudflare Ruleset API for every rule phase (WAF, Rate Limiting,
  Transform, Redirect, Configuration, Origin, Cache, Header rules) and writes:
    - docs/security/cf-rules-dump.json   — raw API output for source of truth
    - docs/security/cloudflare-rules.md  — human-readable summary for GitHub

  Required token permissions:
    Zone - WAF                   Edit
    Zone - Transform Rules       Edit
    Zone - Settings              Edit
    Zone - Firewall Services     Edit

.EXAMPLE
  # Set token, then run from repo root:
  $env:CF_API_TOKEN = "your-token-here"
  .\infra\export-cf-rules.ps1

.EXAMPLE
  # Redact your home IP in the output (recommended before committing):
  .\infra\export-cf-rules.ps1 -RedactIp "[ADMIN-IP]"
#>

param(
    [string]$Zone      = "aboutcloud.io",
    [string]$OutDir    = "docs\security",
    [string]$RedactIp  = ""
)

# ── Token ──────────────────────────────────────────────────────────────────────
$Token = $env:CF_API_TOKEN
if (-not $Token) {
    throw "Set the CF_API_TOKEN environment variable before running this script."
}

$H    = @{ Authorization = "Bearer $Token"; "Content-Type" = "application/json" }
$Base = "https://api.cloudflare.com/client/v4"

# ── Resolve Zone ───────────────────────────────────────────────────────────────
Write-Host "Resolving zone: $Zone ..." -ForegroundColor Cyan
$ZoneObj = (Invoke-RestMethod "$Base/zones?name=$Zone" -Headers $H).result[0]
if (-not $ZoneObj) { throw "Zone '$Zone' not found or token lacks Zone read access." }
$ZoneId = $ZoneObj.id
Write-Host "  Zone ID: $ZoneId" -ForegroundColor DarkGray

# ── Phases to Fetch ────────────────────────────────────────────────────────────
$Phases = [ordered]@{
    "Custom WAF Rules"          = "http_request_firewall_custom"
    "Rate Limiting"             = "http_ratelimit"
    "URL Rewrite Rules"         = "http_request_transform"
    "Redirect Rules"            = "http_request_redirect"
    "Configuration Rules"       = "http_config_settings"
    "Origin Rules"              = "http_request_origin"
    "Cache Rules"               = "http_request_cache_settings"
    "Response Header Transform" = "http_response_headers_transform"
    "Request Header Transform"  = "http_request_late_transform"
}

$Export = [ordered]@{
    zone     = $Zone
    zoneId   = $ZoneId
    exported = (Get-Date -Format "yyyy-MM-ddTHH:mm:ssZ")
    rulesets = [ordered]@{}
}

foreach ($Label in $Phases.Keys) {
    $Phase = $Phases[$Label]
    try {
        $R = Invoke-RestMethod "$Base/zones/$ZoneId/rulesets/phases/$Phase/entrypoint" -Headers $H -ErrorAction Stop
        $Count = if ($R.result.rules) { $R.result.rules.Count } else { 0 }
        $Export.rulesets[$Label] = $R.result
        Write-Host ("  [OK] {0,-30} {1} rule(s)" -f $Label, $Count) -ForegroundColor Green
    } catch {
        $Export.rulesets[$Label] = $null
        Write-Host ("  [--] {0,-30} empty / not enabled" -f $Label) -ForegroundColor DarkGray
    }
}

# ── Ensure Output Dir ──────────────────────────────────────────────────────────
if (-not (Test-Path $OutDir)) { New-Item -ItemType Directory -Path $OutDir -Force | Out-Null }

# ── Write JSON ─────────────────────────────────────────────────────────────────
$Json = $Export | ConvertTo-Json -Depth 20
if ($RedactIp) { $Json = $Json -replace [regex]::Escape($RedactIp), "[REDACTED]" }

$JsonPath = Join-Path $OutDir "cf-rules-dump.json"
$Json | Out-File $JsonPath -Encoding utf8
Write-Host "`nSaved JSON : $JsonPath" -ForegroundColor Cyan

# ── Write Markdown Summary ─────────────────────────────────────────────────────
$Md = [System.Text.StringBuilder]::new()
$null = $Md.AppendLine("# Cloudflare Security Rules — $Zone")
$null = $Md.AppendLine("")
$null = $Md.AppendLine("> Auto-generated by ``infra/export-cf-rules.ps1`` on $(Get-Date -Format 'yyyy-MM-dd').")
$null = $Md.AppendLine("> Source of truth: Cloudflare dashboard → Security / Rules.")
$null = $Md.AppendLine("")

foreach ($Label in $Export.rulesets.Keys) {
    $Ruleset = $Export.rulesets[$Label]
    $Rules   = if ($Ruleset -and $Ruleset.rules) { $Ruleset.rules } else { @() }

    $null = $Md.AppendLine("## $Label")
    $null = $Md.AppendLine("")

    if ($Rules.Count -eq 0) {
        $null = $Md.AppendLine("_No rules configured._")
        $null = $Md.AppendLine("")
        continue
    }

    $null = $Md.AppendLine("| # | Name | Action | Enabled |")
    $null = $Md.AppendLine("|---|------|--------|---------|")

    $i = 1
    foreach ($Rule in $Rules) {
        $Name    = if ($Rule.description) { $Rule.description } else { $Rule.ref }
        $Action  = if ($Rule.action) { $Rule.action } else { "—" }
        $Enabled = if ($Rule.enabled -eq $false) { "No" } else { "Yes" }
        $null = $Md.AppendLine("| $i | $Name | $Action | $Enabled |")
        $i++
    }

    $null = $Md.AppendLine("")

    $i = 1
    foreach ($Rule in $Rules) {
        $Name = if ($Rule.description) { $Rule.description } else { "Rule $i" }
        $Expr = if ($Rule.expression) { $Rule.expression } else { "_(legacy / no expression)_" }
        if ($RedactIp) { $Expr = $Expr -replace [regex]::Escape($RedactIp), "[ADMIN-IP]" }
        $null = $Md.AppendLine("### $i. $Name")
        $null = $Md.AppendLine("")
        $null = $Md.AppendLine("``````")
        $null = $Md.AppendLine($Expr)
        $null = $Md.AppendLine("``````")
        $null = $Md.AppendLine("")
        $i++
    }
}

$MdContent = $Md.ToString()
if ($RedactIp) { $MdContent = $MdContent -replace [regex]::Escape($RedactIp), "[ADMIN-IP]" }

$MdPath = Join-Path $OutDir "cloudflare-rules.md"
$MdContent | Out-File $MdPath -Encoding utf8
Write-Host "Saved MD   : $MdPath" -ForegroundColor Cyan

if ($RedactIp) {
    Write-Host "`nIP $RedactIp redacted as [ADMIN-IP] in all output." -ForegroundColor Yellow
} else {
    Write-Host "`nWARNING: IP addresses are NOT redacted. Review output before committing." -ForegroundColor Red
}
